/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisuellDiskriminierenRouteImport } from './routes/visuell-diskriminieren'
import { Route as IndexRouteImport } from './routes/index'

const VisuellDiskriminierenRoute = VisuellDiskriminierenRouteImport.update({
  id: '/visuell-diskriminieren',
  path: '/visuell-diskriminieren',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/visuell-diskriminieren': typeof VisuellDiskriminierenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/visuell-diskriminieren': typeof VisuellDiskriminierenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/visuell-diskriminieren': typeof VisuellDiskriminierenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/visuell-diskriminieren'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/visuell-diskriminieren'
  id: '__root__' | '/' | '/visuell-diskriminieren'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VisuellDiskriminierenRoute: typeof VisuellDiskriminierenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visuell-diskriminieren': {
      id: '/visuell-diskriminieren'
      path: '/visuell-diskriminieren'
      fullPath: '/visuell-diskriminieren'
      preLoaderRoute: typeof VisuellDiskriminierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VisuellDiskriminierenRoute: VisuellDiskriminierenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
